services:
  - type: web
    name: django-backend
    runtime: python
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: asrdata
          property: connectionString
      - key: SECRET_KEY
        generateValue: true