services:
  - type: web
    name: django-backend
    runtime: python
    buildCommand: "./backend/build.sh"
    startCommand: "gunicorn backend.your_project_name.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-postgres-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"